# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAddress',
            fields=[
                ('acc_add_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='accounts.account')),
                ('house_building_number', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision_village', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBan',
            fields=[
                ('acc_ban_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ban', serialize=False, to='accounts.account')),
                ('reason_ban', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to='accounts.account')),
                ('profile_photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadAdmin',
            fields=[
                ('head_admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='head_admin_profile', serialize=False, to='accounts.account')),
                ('profile_photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mechanic_profile', serialize=False, to='accounts.account')),
                ('profile_photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ranking', models.CharField(choices=[('standard', 'Standard'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='standard', max_length=20)),
                ('is_working_for_shop', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('working', 'Working')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('shop_owner_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop_owner_profile', serialize=False, to='accounts.account')),
                ('profile_photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('owns_shop', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('acc_rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_role', models.CharField(choices=[('client', 'Client'), ('mechanic', 'Mechanic'), ('shop_owner', 'Shop Owner'), ('admin', 'Admin'), ('head_admin', 'Head Admin')], max_length=30)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountWarning',
            fields=[
                ('acc_war_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_warning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_issued', to='accounts.account')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_received', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert'), ('promotional', 'Promotional')], default='info', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('reset_token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAccount',
            fields=[
                ('rep_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken')], default='pending', max_length=30)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action_notes', models.TextField(blank=True, null=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='accounts.account')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('token_purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('tokens_amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchases', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to='accounts.account')),
                ('profile_photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_created', to='accounts.account')),
            ],
        ),
    ]
