# Generated by Django 5.2.8 on 2025-11-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='token_wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='token_wallet',
            field=models.IntegerField(default=0),
        ),
    ]
