# Generated by Django 5.2.8 on 2025-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mechanic_token_wallet_shopowner_token_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
