# Generated by Django 5.2.8 on 2025-11-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mechanic_bio_shopowner_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRejection',
            fields=[
                ('rejection_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_rejection', to='accounts.account')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_made', to='accounts.account')),
            ],
            options={
                'ordering': ['-rejected_at'],
            },
        ),
    ]
