# Generated by Django 5.2.8 on 2025-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationrejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
