# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('refunded', 'refunded'), ('back_jobs', 'back_jobs'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled'), ('dispute', 'dispute')], default='active', max_length=30)),
                ('amount_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='BackJobsBooking',
            fields=[
                ('back_jobs_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_jobs_requests', to='accounts.account')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_jobs', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveBooking',
            fields=[
                ('active_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('before_picture_service', models.CharField(blank=True, max_length=1024, null=True)),
                ('after_picture_service', models.CharField(blank=True, max_length=1024, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_booking', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('cancelled_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('cancelled_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='bookings.booking')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations_made', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBookingList',
            fields=[
                ('client_booking_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_client_lists', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_list', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequestList',
            fields=[
                ('client_request_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_list', to='accounts.client')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_client_lists', to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedBooking',
            fields=[
                ('completed_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_booking', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('complainer_role', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint_against_role', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('issue_picture', models.CharField(blank=True, max_length=1024, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_disputes', to='accounts.admin')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.booking')),
                ('complainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_made', to='accounts.account')),
                ('complaint_against', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_received', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='RefundedBooking',
            fields=[
                ('refunded_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to='accounts.admin')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.booking')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduledBooking',
            fields=[
                ('rescheduled_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=1024, null=True)),
                ('requested_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='bookings.booking')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_requests', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='StatusRequest',
            fields=[
                ('status_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_requests', to='requests.request')),
            ],
        ),
    ]
