# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_banner', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('worth_token', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAddOn',
            fields=[
                ('service_add_on_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServiceInclude',
            fields=[
                ('service_include_id', models.AutoField(primary_key=True, serialize=False)),
                ('include_description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_services', to='services.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_services', to='shop.shop')),
            ],
            options={
                'unique_together': {('service', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='ShopServiceMechanic',
            fields=[
                ('shop_service_mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_service_assignments', to='accounts.mechanic')),
                ('shop_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_service_mechanics', to='services.shopservice')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_services', to='accounts.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_services', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'mechanic')},
            },
        ),
    ]
