# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('custom', 'custom'), ('direct', 'direct'), ('emergency', 'emergency')], max_length=20)),
                ('request_status', models.CharField(choices=[('pending', 'pending'), ('qouted', 'qouted'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.client')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_requests', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='custom_request', serialize=False, to='requests.request')),
                ('description', models.TextField(blank=True, null=True)),
                ('concern_picture', models.CharField(blank=True, max_length=1024, null=True)),
                ('providers_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emergency_request', serialize=False, to='requests.request')),
                ('description', models.TextField(blank=True, null=True)),
                ('concern_picture', models.CharField(blank=True, max_length=1024, null=True)),
                ('providers_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectRequestAddOn',
            fields=[
                ('direct_request_add_on_id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_request_add_ons', to='requests.request')),
                ('service_add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_request_addon_of', to='services.serviceaddon')),
            ],
        ),
        migrations.CreateModel(
            name='QuotedRequestItem',
            fields=[
                ('custom_request_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='requests.customrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DirectRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='direct_request', serialize=False, to='requests.request')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_requests', to='services.service')),
            ],
        ),
    ]
