# Generated by Django 5.2.8 on 2025-12-18 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_customrequest_concern_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedrequestitem',
            name='direct_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='requests.directrequest'),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='concern_picture',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='concern_picture',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quotedrequestitem',
            name='custom_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='requests.customrequest'),
        ),
    ]
