# Generated by Django 5.2.8 on 2025-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_customrequest_concern_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='concern_picture',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='concern_picture',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
