# Generated by Django 5.2.8 on 2025-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_customrequest_concern_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='concern_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='concern_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
