# Generated by Django 5.2.8 on 2025-12-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_quotedrequestitem_direct_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directrequest',
            name='providers_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
