# Generated by Django 5.2.8 on 2025-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_customrequest_concern_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
