# Generated by Django 5.2.8 on 2025-12-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_add_providers_note_to_direct_request'),
        ('requests', '0007_alter_concern_picture_fields'),
    ]

    operations = [
    ]
