# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('specialty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSpecialty',
            fields=[
                ('shop_specialty_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='shop.shop')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_links', to='specialties.specialty')),
            ],
            options={
                'unique_together': {('shop', 'specialty')},
            },
        ),
        migrations.CreateModel(
            name='MechanicSpecialty',
            fields=[
                ('mechanic_specialty_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='accounts.mechanic')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_links', to='specialties.specialty')),
            ],
            options={
                'unique_together': {('mechanic', 'specialty')},
            },
        ),
    ]
