# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicDocument',
            fields=[
                ('mechanic_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('license', 'license'), ('certification', 'certification'), ('ID', 'ID'), ('others', 'others')], max_length=50)),
                ('document_file', models.CharField(max_length=1024)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDocument',
            fields=[
                ('shop_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('business_permit', 'business_permit'), ('mayor_permit', 'mayor_permit'), ('BIR_registration', 'BIR_registration'), ('occupancy_permit', 'occupancy_permit'), ('others', 'others')], max_length=50)),
                ('document_file', models.CharField(max_length=1024)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwnerDocument',
            fields=[
                ('shop_owner_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('business_permit', 'business_permit'), ('mayor_permit', 'mayor_permit'), ('BIR_registration', 'BIR_registration'), ('ID', 'ID'), ('others', 'others')], max_length=50)),
                ('document_file', models.CharField(max_length=1024)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.shopowner')),
            ],
        ),
    ]
