# Generated by Django 5.2.8 on 2025-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicdocument',
            name='document_file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shopdocument',
            name='document_file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shopownerdocument',
            name='document_file',
            field=models.TextField(),
        ),
    ]
