# Generated by Django 5.2.8 on 2025-12-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admin_permissions'),
        ('bookings', '0001_initial'),
        ('payment', '0003_tokenpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('advance', 'Advance Payment')], default='full', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('advance_paid', 'Advance Paid'), ('fully_paid', 'Fully Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Service'), ('other', 'Other')], default='gcash', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_proof', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='bookings.booking')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
